#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jul 21 19:48:36 EDT 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Pixel-Perfect-1-5-1.zip
enableShaders=true
